In [7]:
import torch
import numpy as np
import pandas as pd
import datetime
import torchvision
from torch.utils.tensorboard import SummaryWriter

In [17]:
a = torch.rand((3,3), dtype = torch.float)*10
b = torch.rand((3,3), dtype = torch.float)*10

In [6]:
print(a)
print(b)

tensor([[5.6764, 3.3362, 7.6019],
        [5.7203, 6.8302, 9.5461],
        [4.3806, 8.1220, 3.1774]])
tensor([[3.2793, 3.8742, 8.0686],
        [6.5832, 5.3078, 8.6523],
        [3.1943, 2.0256, 4.3613]])


In [7]:
print(a + b)
print(a - b)
print(a*b)
print(a/b)

tensor([[ 8.9557,  7.2105, 15.6705],
        [12.3035, 12.1380, 18.1984],
        [ 7.5749, 10.1476,  7.5387]])
tensor([[ 2.3971, -0.5380, -0.4667],
        [-0.8629,  1.5224,  0.8938],
        [ 1.1864,  6.0964, -1.1839]])
tensor([[18.6145, 12.9254, 61.3366],
        [37.6578, 36.2536, 82.5958],
        [13.9930, 16.4519, 13.8576]])
tensor([[1.7310, 0.8611, 0.9422],
        [0.8689, 1.2868, 1.1033],
        [1.3714, 4.0097, 0.7285]])


In [10]:
std, mean = torch.std_mean(a)
sum = torch.sum(a)
print(sum)
print(std)
print(mean)

tensor(54.3911)
tensor(2.1847)
tensor(6.0435)


In [12]:
npc = np.array([1,2,3])
pyc = torch.tensor(npc)
print(pyc)

npa = np.array(a)
print(npa)

tensor([1, 2, 3], dtype=torch.int32)
[[5.6763678 3.336244  7.601881 ]
 [5.7202888 6.83022   9.546087 ]
 [4.3806453 8.122     3.1774068]]


In [16]:
a = torch.rand((4,5), dtype = torch.float)*10
print(a)
print(a.view((10,2)))
a_reshaped = a.reshape((1,20))
print(a_reshaped)

tensor([[1.3532e+00, 6.0391e+00, 7.0622e+00, 2.5440e+00, 5.8133e+00],
        [5.9183e+00, 2.1062e+00, 5.2148e-03, 9.1243e+00, 9.2477e+00],
        [4.4478e-01, 8.7339e+00, 1.7303e+00, 1.3149e+00, 4.0917e+00],
        [4.9170e+00, 1.5890e-01, 1.8801e+00, 5.2332e+00, 8.3610e+00]])
tensor([[1.3532e+00, 6.0391e+00],
        [7.0622e+00, 2.5440e+00],
        [5.8133e+00, 5.9183e+00],
        [2.1062e+00, 5.2148e-03],
        [9.1243e+00, 9.2477e+00],
        [4.4478e-01, 8.7339e+00],
        [1.7303e+00, 1.3149e+00],
        [4.0917e+00, 4.9170e+00],
        [1.5890e-01, 1.8801e+00],
        [5.2332e+00, 8.3610e+00]])
tensor([[1.3532e+00, 6.0391e+00, 7.0622e+00, 2.5440e+00, 5.8133e+00, 5.9183e+00,
         2.1062e+00, 5.2148e-03, 9.1243e+00, 9.2477e+00, 4.4478e-01, 8.7339e+00,
         1.7303e+00, 1.3149e+00, 4.0917e+00, 4.9170e+00, 1.5890e-01, 1.8801e+00,
         5.2332e+00, 8.3610e+00]])


In [19]:
a = torch.rand((3,3), dtype = torch.float)*10
b = torch.rand((3,3), dtype = torch.float)*10

print(a)
print(b)

print(torch.cat((a,b), 0))
print(torch.cat((a,b), 1))

tensor([[8.1426, 2.6722, 5.8148],
        [1.5374, 3.9404, 2.8217],
        [8.5043, 3.7518, 0.3538]])
tensor([[3.7322, 3.2374, 0.4156],
        [7.1916, 8.7881, 5.4850],
        [3.1763, 8.2534, 7.9722]])
tensor([[8.1426, 2.6722, 5.8148],
        [1.5374, 3.9404, 2.8217],
        [8.5043, 3.7518, 0.3538],
        [3.7322, 3.2374, 0.4156],
        [7.1916, 8.7881, 5.4850],
        [3.1763, 8.2534, 7.9722]])
tensor([[8.1426, 2.6722, 5.8148, 3.7322, 3.2374, 0.4156],
        [1.5374, 3.9404, 2.8217, 7.1916, 8.7881, 5.4850],
        [8.5043, 3.7518, 0.3538, 3.1763, 8.2534, 7.9722]])


In [21]:
c = torch.cat((a,b), 0)
print(c[2,2])
print(c[2:,1])

tensor(0.3538)
tensor([3.7518, 3.2374, 8.7881, 8.2534])


In [25]:
len = int(input("Enter the size of the tensor you want to find the dot product of: "))
a = torch.rand(len, dtype = torch.float)*10
b = torch.rand(len, dtype = torch.float)*10

print(f"the first tensor will be {a}\nthe second tensor will be {b}")
print(f"their dot product is: {torch.dot(a,b)}")
print(f"their cross product is: {torch.linalg.cross(a,b)}")

Enter the size of the tensor you want to find the dot product of:  3


the first tensor will be tensor([0.1062, 8.1136, 8.5954])
the second tensor will be tensor([6.4452, 5.9358, 6.0402])
their dot product is: 100.76303100585938
their cross product is: tensor([ -2.0137,  54.7578, -51.6633])


In [26]:
print(torch.cuda.is_available())

True


In [117]:
a = torch.rand((3,3), dtype = torch.float)*10

a_normalized = (a - torch.min(a))/(torch.max(a) - torch.min(a))

print(a)
print(f"the normalized versions of the tensor is: \n{a_normalized}")

x = torch.tensor([2.0], requires_grad = True)
y = pow(x,2) + 3*x + 5
print(f"gradient of equation is: {torch.autograd.grad(y, inputs = x)}")

tensor([[2.5163, 6.1333, 3.1005],
        [7.1179, 6.3522, 7.8089],
        [0.2477, 6.8485, 5.7656]])
the normalized versions of the tensor is: 
tensor([[0.3000, 0.7784, 0.3773],
        [0.9086, 0.8073, 1.0000],
        [0.0000, 0.8730, 0.7298]])
gradient of equation is: (tensor([7.]),)


In [52]:
#Implement a NN using Pytorch
trainfile = 'mnist_train.csv'
testfile = 'mnist_test.csv'

train_samples = pd.read_csv(trainfile, header = None)
test_samples = pd.read_csv(testfile, header = None)

train_Labels = torch.tensor(train_samples.pop(0))
test_Labels = torch.tensor(test_samples.pop(0))

train_samples = torch.tensor(train_samples.values, dtype = torch.float)
test_samples = torch.tensor(test_samples.values, dtype = torch.float)

print(train_Labels[0])
print(test_Labels[0])

tensor(5)
tensor(7)


In [72]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        self.Lin1 = torch.nn.Linear(784,64)
        self.drop1 = torch.nn.Dropout(p=0.2)
        self.Lin2 = torch.nn.Linear(64,30)
        self.drop2 = torch.nn.Dropout(p=0.2)
        self.Lin3 = torch.nn.Linear(30,10)

    # x represents our data
    def forward(self, x):
        x = torch.flatten(x, start_dim = 1)
        x = torch.nn.ReLU()(self.Lin1(x))
        x = self.drop1(x)
        x = torch.nn.ReLU()(self.Lin2(x))
        x = self.drop2(x)
        x = self.Lin3(x)
        
        output = torch.nn.functional.softmax(x, dim = 1)
        return output

In [73]:
simple_Net = Net()
optimizer = torch.optim.SGD(simple_Net.parameters(), lr=0.01)
loss_fn = torch.nn.CrossEntropyLoss()

transform = torchvision.transforms.Compose([torchvision.transforms.ToTensor()])

training_set = torchvision.datasets.MNIST('./data', train=True, transform = transform, download=True)
validation_set = torchvision.datasets.MNIST('./data', train=False, transform = transform, download=True)

# Create data loaders for our datasets; shuffle for training, not for validation
training_loader = torch.utils.data.DataLoader(training_set, batch_size=4, shuffle=True)
validation_loader = torch.utils.data.DataLoader(validation_set, batch_size=4, shuffle=False)

def train_one_epoch(epoch_index, tb_writer):
    running_loss = 0.
    last_loss = 0.

    # Here, we use enumerate(training_loader) instead of
    # iter(training_loader) so that we can track the batch
    # index and do some intra-epoch reporting
    for i, data in enumerate(training_loader):
        # Every data instance is an input + label pair
        inputs, labels = data

        # Zero your gradients for every batch!
        optimizer.zero_grad()

        # Make predictions for this batch
        outputs = simple_Net(inputs)

        # Compute the loss and its gradients
        loss = loss_fn(outputs, labels)
        loss.backward()

        # Adjust learning weights
        optimizer.step()

        # Gather data and report
        running_loss += loss.item()
        if i % 1000 == 999:
            last_loss = running_loss / 1000 # loss per batch
            print(f'  batch {i + 1} loss: {last_loss}')
            tb_x = epoch_index * len(training_loader) + i + 1
            tb_writer.add_scalar('Loss/train', last_loss, tb_x)
            running_loss = 0.
    
    return last_loss



In [99]:
timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
writer = SummaryWriter('runs/number_recognition{}'.format(timestamp))
epoch_number = 0

EPOCHS = 5

best_vloss = 1_000_000.

for epoch in range(EPOCHS):
    print('EPOCH {}:'.format(epoch_number + 1))

    # Make sure gradient tracking is on, and do a pass over the data
    simple_Net.train(True)
    avg_loss = train_one_epoch(epoch_number, writer)


    running_vloss = 0.0
    # Set the model to evaluation mode, disabling dropout and using population
    # statistics for batch normalization.
    simple_Net.eval()

    # Disable gradient computation and reduce memory consumption.
    with torch.no_grad():
        correct = 0
        for i, vdata in enumerate(validation_loader):
            vinputs, vlabels = vdata
            voutputs = simple_Net(vinputs)
            vouts_indexes = [int(np.argmax(output)) for output in voutputs]
            vloss = loss_fn(voutputs, vlabels)
            running_vloss += vloss

            '''print(vlabels.shape)
            print(vlabels)
            print(voutputs.shape)
            print(vouts_indexes)
            print((vouts_indexes == vlabels))'''


            correct += sum([vout == vl for vout,vl in zip(vouts_indexes,vlabels)])

        accuracy = 100 * correct / len(validation_set)
        print("Accuracy = {}".format(accuracy))

    avg_vloss = running_vloss / (i + 1)
    print('LOSS train {} valid {}'.format(avg_loss, avg_vloss))

    # Log the running loss averaged per batch
    # for both training and validation
    writer.add_scalars('Training vs. Validation Loss',
                    { 'Training' : avg_loss, 'Validation' : avg_vloss },
                    epoch_number + 1)
    writer.flush()

    # Track best performance, and save the model's state
    if avg_vloss < best_vloss:
        best_vloss = avg_vloss
        model_path = 'model_{}_{}'.format(timestamp, epoch_number)
        torch.save(simple_Net.state_dict(), model_path)

    epoch_number += 1

EPOCH 1:
  batch 1000 loss: 1.6898642497062684
  batch 2000 loss: 1.701869018793106
  batch 3000 loss: 1.710561738729477
  batch 4000 loss: 1.6998432521820068
  batch 5000 loss: 1.710086448788643
  batch 6000 loss: 1.7103930699825287
  batch 7000 loss: 1.7060140932798387
  batch 8000 loss: 1.7009531149864197
  batch 9000 loss: 1.6843030613660812
  batch 10000 loss: 1.6924271295070648
  batch 11000 loss: 1.7021549866199492
  batch 12000 loss: 1.7014415531158447
  batch 13000 loss: 1.6904117175340652
  batch 14000 loss: 1.6942654416561127
  batch 15000 loss: 1.6943294664621353
Accuracy = 81.20999908447266
LOSS train 1.6943294664621353 valid 1.6531153917312622
EPOCH 2:
  batch 1000 loss: 1.6888378084897995
  batch 2000 loss: 1.6858132799863816
  batch 3000 loss: 1.6939635347127915
  batch 4000 loss: 1.6879104030132295
  batch 5000 loss: 1.6947157834768296
  batch 6000 loss: 1.6827511801719666
  batch 7000 loss: 1.693055657863617
  batch 8000 loss: 1.6800889637470244
  batch 9000 loss: 1.6

In [114]:
net = torch.nn.Sequential(
    torch.nn.Conv2d(1, 8, 3),
    torch.nn.ReLU(),
    torch.nn.MaxPool2d(kernel_size=2, stride=2),
    torch.nn.Conv2d(8, 16, 3),
    torch.nn.ReLU(),
    torch.nn.MaxPool2d(kernel_size=2, stride=2),
    torch.nn.Flatten(),
    torch.nn.Linear(400, 30),
    torch.nn.ReLU(),
    torch.nn.Linear(30, 10),
    torch.nn.Softmax()
)

In [115]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
loss_fn = torch.nn.CrossEntropyLoss()

transform = torchvision.transforms.Compose([torchvision.transforms.ToTensor()])

training_set = torchvision.datasets.MNIST('./data', train=True, transform = transform, download=True)
validation_set = torchvision.datasets.MNIST('./data', train=False, transform = transform, download=True)

# Create data loaders for our datasets; shuffle for training, not for validation
training_loader = torch.utils.data.DataLoader(training_set, batch_size=4, shuffle=True)
validation_loader = torch.utils.data.DataLoader(validation_set, batch_size=4, shuffle=False)

def train_one_epoch(epoch_index, tb_writer):
    running_loss = 0.
    last_loss = 0.

    # Here, we use enumerate(training_loader) instead of
    # iter(training_loader) so that we can track the batch
    # index and do some intra-epoch reporting
    for i, data in enumerate(training_loader):
        # Every data instance is an input + label pair
        inputs, labels = data

        # Zero your gradients for every batch!
        optimizer.zero_grad()

        # Make predictions for this batch
        outputs = net(inputs)

        # Compute the loss and its gradients
        loss = loss_fn(outputs, labels)
        loss.backward()

        # Adjust learning weights
        optimizer.step()

        # Gather data and report
        running_loss += loss.item()
        if i % 1000 == 999:
            last_loss = running_loss / 1000 # loss per batch
            print(f'  batch {i + 1} loss: {last_loss}')
            tb_x = epoch_index * len(training_loader) + i + 1
            tb_writer.add_scalar('Loss/train', last_loss, tb_x)
            running_loss = 0.
    
    return last_loss



In [116]:
timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
writer = SummaryWriter('runs/number_recognition{}'.format(timestamp))
epoch_number = 0

EPOCHS = 5

best_vloss = 1_000_000.

for epoch in range(EPOCHS):
    print('EPOCH {}:'.format(epoch_number + 1))

    # Make sure gradient tracking is on, and do a pass over the data
    net.train(True)
    avg_loss = train_one_epoch(epoch_number, writer)


    running_vloss = 0.0
    # Set the model to evaluation mode, disabling dropout and using population
    # statistics for batch normalization.
    net.eval()

    # Disable gradient computation and reduce memory consumption.
    with torch.no_grad():
        correct = 0
        for i, vdata in enumerate(validation_loader):
            vinputs, vlabels = vdata
            voutputs = net(vinputs)
            vouts_indexes = [int(np.argmax(output)) for output in voutputs]
            vloss = loss_fn(voutputs, vlabels)
            running_vloss += vloss

            '''print(vlabels.shape)
            print(vlabels)
            print(voutputs.shape)
            print(vouts_indexes)
            print((vouts_indexes == vlabels))'''


            correct += sum([vout == vl for vout,vl in zip(vouts_indexes,vlabels)])

        accuracy = 100 * correct / len(validation_set)
        print("Accuracy = {}".format(accuracy))

    avg_vloss = running_vloss / (i + 1)
    print('LOSS train {} valid {}'.format(avg_loss, avg_vloss))

    # Log the running loss averaged per batch
    # for both training and validation
    writer.add_scalars('Training vs. Validation Loss',
                    { 'Training' : avg_loss, 'Validation' : avg_vloss },
                    epoch_number + 1)
    writer.flush()

    # Track best performance, and save the model's state
    if avg_vloss < best_vloss:
        best_vloss = avg_vloss
        model_path = 'CNNmodel_{}_{}'.format(timestamp, epoch_number)
        torch.save(net.state_dict(), model_path)

    epoch_number += 1

EPOCH 1:
  batch 1000 loss: 2.3025808975696562
  batch 2000 loss: 2.30177400970459
  batch 3000 loss: 2.301076328277588
  batch 4000 loss: 2.299415441274643
  batch 5000 loss: 2.2958686292171477
  batch 6000 loss: 2.274007566690445
  batch 7000 loss: 1.9666945221424104
  batch 8000 loss: 1.7471931159496308
  batch 9000 loss: 1.6902977672815322
  batch 10000 loss: 1.6780843708515167
  batch 11000 loss: 1.656922822356224
  batch 12000 loss: 1.6573207176923752
  batch 13000 loss: 1.6492427184581757
  batch 14000 loss: 1.6352473433017731
  batch 15000 loss: 1.6358036402463914
Accuracy = 83.70999908447266
LOSS train 1.6358036402463914 valid 1.6270028352737427
EPOCH 2:
  batch 1000 loss: 1.6185956604480742
  batch 2000 loss: 1.6249510163068772
  batch 3000 loss: 1.6173874740600587
  batch 4000 loss: 1.6224972891807556
  batch 5000 loss: 1.6182767416238786
  batch 6000 loss: 1.6253835686445237
  batch 7000 loss: 1.613750473856926
  batch 8000 loss: 1.6138449010848999
  batch 9000 loss: 1.6072